default_stages: [pre-commit]

repos:
- repo: https://github.com/python-poetry/poetry
  rev: 2.3.2
  hooks:

  # Check the content of the pyproject.toml file and its consistency with the poetry.lock file
  - id: poetry-check
    name: Poetry check

- repo: local
  hooks:
  # Code formatting

  - id: format
    name: Formatting
    description: Code formatting.
    language: python
    entry: poetry run ruff format
    types: [python]

  - id: linting
    name: Linting
    description: Code linting.
    language: python
    entry: poetry run ruff check --fix
    types: [python]

  # Code analysis

  - id: type-checking
    name: Type checking
    description: Performs static type checking of source code.
    language: python
    entry: poetry run mypy
    types: [python]
    pass_filenames: false

  # Tests

  - id: tests
    name: Tests
    stages: [pre-push]
    language: system
    entry: poetry run pytest --cov
    types: [python]
    pass_filenames: false
