default_stages: [pre-commit]

repos:
 - repo: local

   hooks:

   # Code formatting

   - id: ruff-format
     name: ruff-format
     description: Python code formatting.
     language: python
     entry: ruff format
     types: [python]

   - id: ruff check
     name: ruff check
     language: python
     entry: ruff check .
     args: [--fix, --exit-non-zero-on-fix]
     types: [python]

   # Code analysis

   - id: mypy
     name: mypy
     description: Performs static type checking of source code written in Python.
     language: python
     entry: mypy
     types: [python]
     pass_filenames: false

   - id: pylint
     name: pylint
     description: Performs static analysis of source code written in Python.
     language: python
     entry: pylint
     types: [python]

    # Local tests

   - id: pytest
     name: pytest
     language: python
     entry: pytest
     types: [python]
     pass_filenames: false

   - id: pytest-cov
     name: pytest-cov
     stages: [pre-push]
     language: python
     entry: pytest
     types: [python]
     pass_filenames: false
