[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "sudoku-resolver"
version = "0.1.0"
description = "Solve sudokus using CSPs and Python."
authors = [
    {name = "raphaellndr"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "numpy (==2.2.4)",
    "click (==8.4.2)",
]

[project.scripts]
sudoku-resolver = "sudoku_resolver.__main__:main"

[dependency-groups]
dev = [
    "ruff (==0.15.21)",
    "mypy (==2.2.0)",
    "pre-commit (==4.6.0)",
    "pytest (==9.1.1)",
    "pytest-cov (==7.1.0)",
    "pytest-timeout (==2.4.0)",
]

[tool.poetry]
packages = [
    {include = "sudoku_resolver", from = "src"}
]

[tool.mypy]
files = ["src/sudoku_resolver"]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # isort
    "I",
    # Pylint
    "PL",
    # pydocstyle
    "D",
    # flake8-print
    "T20"
]
ignore = [
    # Disable rule `D401` (`non-imperative-mood`)
    "D401",
    # Disable rule `D213` (`multi-line-summary-second-line`)
    "D213",
    # Disable rule `D203` (`incorrect-blank-line-before-class`)
    "D203",
    # Disable rule `D107` (`undocumented-public-init`)
    "D107",
    # Disable rule `D200` (`unnecessary-multiline-docstring`)
    "D200"
]

[tool.ruff.lint.per-file-ignores]
# Ignore `D`, `PL` and `T20` rules everywhere except for the `src/` directory
"!src/**.py" = [
    "D",
    "PL",
    "T20"
]

[tool.ruff.lint.pylint]
max-args = 8

[tool.coverage.report]
show_missing = true
fail_under = 10

[tool.coverage.run]
source = ["src/sudoku_resolver"]
