#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/..";pwd)"
cd "$PROJECT_ROOT"

if [[ "$#" -gt 0 ]] && [[ "$1" = "check" ]]; then
    # Check only

    echo "████████████████████████ ruff format ███████████████████████████████"
    poetry run ruff format --check src/sudoku_resolver tests
    echo "████████████████████████████   ruff   █████████████████████████████"
    poetry run ruff check src/sudoku_resolver tests
else
    # Reformat

    echo "████████████████████████ ruff format ███████████████████████████████"
    poetry run ruff format src/sudoku_resolver tests
    echo "████████████████████████████   ruff   █████████████████████████████"
    poetry run ruff check --fix src/sudoku_resolver tests
fi
